---
- name: "Run premigration tasks on Windows machines" 
  hosts: all
  vars:
    ansible_connection: "{{ ansible_connection }}"
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_winrm_server_cert_validation: ignore
    ignore_errors: yes
  tasks:
    - name: "Copy poweshell script file"
      win_copy:
        src: files/pre-migrate.ps1
        dest: 'C:\temp\'
        remote_src: no

    - name: "Run Powershell command"
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/pre-migrate.ps1
...
